name: CI Pipeline Agregado

on:
  push:
    branches: [ master, ci-setup, practica ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests and generate JUnit report
        run: |
          pytest --junitxml=report.xml
          
      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: pytest
          path: report.xml
          reporter: github-actions